DROP TABLE IF EXISTS PET;

CREATE TABLE PET (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  pet_name VARCHAR(250) NOT NULL,
  pet_age VARCHAR(250) NOT NULL,
   pet_guardian VARCHAR(250) NOT NULL,
    phone_number VARCHAR(45) NOT NULL
);